name: neurolens
description: Cross-platform app for monitoring mental well-being
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.1
  fl_chart: ^0.65.0
  intl: ^0.18.1
  camera: ^0.10.5+5
  camera_windows: ^0.2.1+6
  camera_android: ^0.10.8+11
  path_provider: ^2.1.1
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  uuid: ^4.2.2
  crypto: ^3.0.3
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/strings.json